repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
    args: [--assume-in-merge]
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.19
  hooks:
  - id: mdformat
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.3
  hooks:
  - id: ruff
    types_or: [ python, pyi ]
    args: [ --fix ]
  - id: ruff-format
    types_or: [ python, pyi ]
