name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest .

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref $${{ github.event.pull_request.head.sha }}
